package Views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.regex.Pattern;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.Clip;
import javax.sound.sampled.AudioSystem;
import Utils.Utils;
import javax.swing.ImageIcon;

/**
 *
 * @author Ayyoob Rifdhi
 * LAN Messenger - HCI Assignment 1 for Curtin University
 */
public class LAN_Messenger_SignUp extends javax.swing.JFrame {

    /**
     * Creates new form LAN_Messenger_SignUp
     */
    public LAN_Messenger_SignUp() {
        initComponents();
        //To keep the window in the middle of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        //setting the background to transparent        
        Signup.setBackground(new Color(0,0,0,0));
        username_textfield_signup.setBackground(new Color(0,0,0,0));
        email_field_signup.setBackground(new Color(0,0,0,0));
        password_field_signup.setBackground(new Color(0,0,0,0));
        Signup.setVisible(false);
        ResetPassword.setVisible(false);
        Login.setBackground(new Color(0,0,0,0));
        username_textfield_login.setBackground(new Color(0,0,0,0));
        password_field_login.setBackground(new Color(0,0,0,0));
        label_pwd_reset.setBackground(new Color(0,0,0,0));
        label_pwd_reset1.setBackground(new Color(0,0,0,0));
        email_label_pwd_reset.setBackground(new Color(0,0,0,0));
        email_field_pwd_reset.setBackground(new Color(0,0,0,0));
        
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        error_login = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        password_field_login = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        username_textfield_login = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ResetPassword = new javax.swing.JPanel();
        label_pwd_reset = new javax.swing.JTextField();
        label_pwd_reset1 = new javax.swing.JTextField();
        email_field_pwd_reset = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        error_email_pwd_reset = new javax.swing.JLabel();
        email_label_pwd_reset = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        submit_btn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Signup = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        upload_btn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        error_username_signup = new javax.swing.JLabel();
        error_password_signup = new javax.swing.JLabel();
        error_email_signup = new javax.swing.JLabel();
        email_field_signup = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        password_field_signup = new javax.swing.JPasswordField();
        username_textfield_signup = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        signup_btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(new java.awt.CardLayout());

        Login.setMinimumSize(new java.awt.Dimension(800, 500));
        Login.setPreferredSize(new java.awt.Dimension(800, 500));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        error_login.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        error_login.setForeground(new java.awt.Color(204, 0, 0));
        Login.add(error_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, 20));

        login_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        login_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login_btn.setBorderPainted(false);
        login_btn.setOpaque(false);
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        Login.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 130, 40));

        jLabel11.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Forgotten your password? Reset Password");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        Login.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 290, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Don't have a login yet? Sign up");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        Login.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 260, -1));
        Login.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 280, 20));
        Login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 280, -1));

        password_field_login.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        password_field_login.setForeground(new java.awt.Color(153, 153, 153));
        password_field_login.setText("password");
        password_field_login.setBorder(null);
        password_field_login.setOpaque(false);
        password_field_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_field_loginFocusGained(evt);
            }
        });
        Login.add(password_field_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 280, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hello, User!");
        Login.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 100, 30));

        username_textfield_login.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        username_textfield_login.setForeground(new java.awt.Color(153, 153, 153));
        username_textfield_login.setText("Enter Username");
        username_textfield_login.setBorder(null);
        username_textfield_login.setOpaque(false);
        username_textfield_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_textfield_loginFocusGained(evt);
            }
        });
        Login.add(username_textfield_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 280, 40));

        jCheckBox1.setSelected(true);
        jCheckBox1.setOpaque(false);
        Login.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 20, 20));

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sign In As Available");
        Login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 140, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("You are connecting to 220.213.410.101");
        Login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 260, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        Login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 80, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        Login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 80, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right_bckgrnd_new.png"))); // NOI18N
        Login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 410, 500));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left_bckgrnd_new.png"))); // NOI18N
        Login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 500));

        getContentPane().add(Login, "card4");

        ResetPassword.setMinimumSize(new java.awt.Dimension(800, 500));
        ResetPassword.setPreferredSize(new java.awt.Dimension(800, 500));
        ResetPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_pwd_reset.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        label_pwd_reset.setForeground(new java.awt.Color(153, 153, 153));
        label_pwd_reset.setText("Let us email you a password reset link.");
        label_pwd_reset.setBorder(null);
        label_pwd_reset.setOpaque(false);
        ResetPassword.add(label_pwd_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 420, 30));

        label_pwd_reset1.setEditable(false);
        label_pwd_reset1.setBackground(new java.awt.Color(0, 0, 0));
        label_pwd_reset1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        label_pwd_reset1.setForeground(new java.awt.Color(255, 255, 255));
        label_pwd_reset1.setText("Forgotten your password?");
        label_pwd_reset1.setBorder(null);
        label_pwd_reset1.setOpaque(false);
        ResetPassword.add(label_pwd_reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 180, 30));

        email_field_pwd_reset.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        email_field_pwd_reset.setForeground(new java.awt.Color(153, 153, 153));
        email_field_pwd_reset.setText("Enter Email Address");
        email_field_pwd_reset.setBorder(null);
        email_field_pwd_reset.setOpaque(false);
        email_field_pwd_reset.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_field_pwd_resetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_field_pwd_resetFocusLost(evt);
            }
        });
        ResetPassword.add(email_field_pwd_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 280, 40));

        jLabel9.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Reset Password");
        ResetPassword.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 160, 30));

        error_email_pwd_reset.setFont(new java.awt.Font("Nirmala UI", 1, 11)); // NOI18N
        error_email_pwd_reset.setForeground(new java.awt.Color(255, 255, 255));
        ResetPassword.add(error_email_pwd_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 230, 20));

        email_label_pwd_reset.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        email_label_pwd_reset.setForeground(new java.awt.Color(255, 255, 255));
        email_label_pwd_reset.setText("Email");
        ResetPassword.add(email_label_pwd_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 80, -1));
        ResetPassword.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 280, -1));

        submit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Submit.png"))); // NOI18N
        submit_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        submit_btn.setBorderPainted(false);
        submit_btn.setOpaque(false);
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        ResetPassword.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right_bckgrnd_new.png"))); // NOI18N
        ResetPassword.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 410, 500));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left_bckgrnd_new.png"))); // NOI18N
        ResetPassword.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 500));

        getContentPane().add(ResetPassword, "card2");

        Signup.setMinimumSize(new java.awt.Dimension(800, 500));
        Signup.setPreferredSize(new java.awt.Dimension(800, 500));
        Signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        Signup.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));
        Signup.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        upload_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Upload.png"))); // NOI18N
        upload_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        upload_btn.setBorderPainted(false);
        upload_btn.setOpaque(false);
        upload_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_btnActionPerformed(evt);
            }
        });
        Signup.add(upload_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 110, 40));

        jLabel18.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Profile Picture");
        Signup.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 120, -1));

        error_username_signup.setFont(new java.awt.Font("Nirmala UI", 1, 11)); // NOI18N
        error_username_signup.setForeground(new java.awt.Color(255, 255, 255));
        Signup.add(error_username_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        error_password_signup.setFont(new java.awt.Font("Nirmala UI", 1, 11)); // NOI18N
        error_password_signup.setForeground(new java.awt.Color(255, 255, 255));
        Signup.add(error_password_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 230, 20));

        error_email_signup.setFont(new java.awt.Font("Nirmala UI", 1, 11)); // NOI18N
        error_email_signup.setForeground(new java.awt.Color(255, 255, 255));
        Signup.add(error_email_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 230, 20));

        email_field_signup.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        email_field_signup.setForeground(new java.awt.Color(153, 153, 153));
        email_field_signup.setText("Enter Email Address");
        email_field_signup.setBorder(null);
        email_field_signup.setOpaque(false);
        email_field_signup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_field_signupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_field_signupFocusLost(evt);
            }
        });
        Signup.add(email_field_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 280, 40));

        jLabel17.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Email");
        Signup.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 80, -1));
        Signup.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 280, -1));
        Signup.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 280, 20));
        Signup.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 280, -1));

        password_field_signup.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        password_field_signup.setForeground(new java.awt.Color(153, 153, 153));
        password_field_signup.setText("password");
        password_field_signup.setBorder(null);
        password_field_signup.setOpaque(false);
        password_field_signup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_field_signupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_field_signupFocusLost(evt);
            }
        });
        Signup.add(password_field_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 280, 30));

        username_textfield_signup.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        username_textfield_signup.setForeground(new java.awt.Color(153, 153, 153));
        username_textfield_signup.setText("Enter Username");
        username_textfield_signup.setBorder(null);
        username_textfield_signup.setOpaque(false);
        username_textfield_signup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_textfield_signupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_textfield_signupFocusLost(evt);
            }
        });
        Signup.add(username_textfield_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 280, 40));

        jLabel13.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password");
        Signup.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 80, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Username");
        Signup.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 80, -1));

        signup_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Signup.png"))); // NOI18N
        signup_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        signup_btn.setBorderPainted(false);
        signup_btn.setOpaque(false);
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_btnActionPerformed(evt);
            }
        });
        Signup.add(signup_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right_bckgrnd_new.png"))); // NOI18N
        Signup.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 410, 500));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left_bckgrnd_new.png"))); // NOI18N
        Signup.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 500));

        getContentPane().add(Signup, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_btnActionPerformed
        if(error_username_signup.getText().equals("") && error_password_signup.getText().equals("") && error_email_signup.getText().equals("")){
            
            Login.setVisible(true);
            Signup.setVisible(false);
            Utils.playSound("pressSound2.wav");
        }else
            Utils.playSound("pressSound.wav");
    }//GEN-LAST:event_signup_btnActionPerformed

    private void username_textfield_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_textfield_loginFocusGained
        // TODO add your handling code here:
        error_login.setText("");
        String username = username_textfield_login.getText();
        if(username.equals("Enter Username")){
        
             username_textfield_login.setText("");
            
        }
       
    }//GEN-LAST:event_username_textfield_loginFocusGained

    private void password_field_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_field_loginFocusGained
        char[] array = password_field_login.getPassword();
        String password = new String(array);
        if(password.equals("password")){
            password_field_login.setText("");
        }
        
    }//GEN-LAST:event_password_field_loginFocusGained

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        String username,password;
        username = username_textfield_login.getText();
        password = password_field_login.getText();
        
        if(username.equals("Ayyoob")){
            Utils.playSound("pressSound2.wav");
            AppShell main = new AppShell();
            main.setVisible(true);
            this.setVisible(false);
        }else{
            error_login.setText("Username and Password do not match!");
            Utils.playSound("pressSound.wav");
        }
        
       
    }//GEN-LAST:event_login_btnActionPerformed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
        Login.setVisible(false);
        Signup.setVisible(true);
        Utils.playSound("pressSound2.wav");
    }//GEN-LAST:event_jLabel10MousePressed

    private void username_textfield_signupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_textfield_signupFocusLost
        // TODO add your handling code here:
        String username = username_textfield_signup.getText();
        boolean valid = (username != null) && username.matches("[A-za-z0-9_]+");
        
        if(!valid){ 
            
            error_username_signup.setText("Username can only contain letters, numbers, and underscores.");
       
        }
    }//GEN-LAST:event_username_textfield_signupFocusLost

    private void password_field_signupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_field_signupFocusLost
        // TODO add your handling code here:
        char[] array = password_field_signup.getPassword();
        String password = new String(array);
        if(password.length() < 8){
            
            error_password_signup.setText("Password must contain atleast 8 characters.");
            
        }
        
    }//GEN-LAST:event_password_field_signupFocusLost

    private void username_textfield_signupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_textfield_signupFocusGained
        
        String username = username_textfield_signup.getText();
        if(username.equals("Enter Username")){
        
            username_textfield_signup.setText("");
            
        }
        
        error_username_signup.setText("");
    }//GEN-LAST:event_username_textfield_signupFocusGained

    private void password_field_signupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_field_signupFocusGained
        
        char[] array = password_field_login.getPassword();
        String password = new String(array);
        if(password.equals("password")){
            password_field_signup.setText("");
        }
        
        error_password_signup.setText("");
    }//GEN-LAST:event_password_field_signupFocusGained

    private void email_field_signupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_field_signupFocusLost
        
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$";
        String email = email_field_signup.getText();
        Pattern pattern = Pattern.compile(emailRegex);
        if(email == null)
            error_email_signup.setText("Enter Valid Email Address!");
        else{
            boolean valid = pattern.matcher(email).matches();
            if(!valid){
            error_email_signup.setText("Enter Valid Email Address!");
            }
        }
    }//GEN-LAST:event_email_field_signupFocusLost

    private void email_field_signupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_field_signupFocusGained
       
        String email = email_field_signup.getText();
        if(email.equals("Enter Email Address")){
        
            email_field_signup.setText("");
            
        }

        error_email_signup.setText("");
    }//GEN-LAST:event_email_field_signupFocusGained

    private void email_field_pwd_resetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_field_pwd_resetFocusGained
        String email = email_field_pwd_reset.getText();
        if(email.equals("Enter Email Address")){
        
            email_field_pwd_reset.setText("");
            
        }

        error_email_pwd_reset.setText("");
    }//GEN-LAST:event_email_field_pwd_resetFocusGained

    private void email_field_pwd_resetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_field_pwd_resetFocusLost
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$";
        String email = email_field_pwd_reset.getText();
        Pattern pattern = Pattern.compile(emailRegex);
        if(email == null)
            error_email_pwd_reset.setText("Enter Valid Email Address!");
        else{
            boolean valid = pattern.matcher(email).matches();
            if(!valid){
            error_email_pwd_reset.setText("Enter Valid Email Address!");
            }
        }
    }//GEN-LAST:event_email_field_pwd_resetFocusLost

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        if(error_email_pwd_reset.getText().equals("")){
            ResetPassword.setVisible(false);
            Login.setVisible(true);
            Utils.playSound("pressSound2.wav");
        }else
            Utils.playSound("pressSound.wav");
    }//GEN-LAST:event_submit_btnActionPerformed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        Utils.playSound("pressSound2.wav");
        Login.setVisible(false);
        ResetPassword.setVisible(true);
    }//GEN-LAST:event_jLabel11MousePressed

    private void upload_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_btnActionPerformed
        ImageIcon image = new ImageIcon(new File("profileicon_white.png").getAbsolutePath());
        jLabel7.setIcon(image);
        jLabel12.setText("Picture Uploaded Successfully!");
        Utils.playSound("pressSound2.wav");
    }//GEN-LAST:event_upload_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAN_Messenger_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAN_Messenger_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAN_Messenger_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAN_Messenger_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAN_Messenger_SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JPanel ResetPassword;
    private javax.swing.JPanel Signup;
    private javax.swing.JTextField email_field_pwd_reset;
    private javax.swing.JTextField email_field_signup;
    private javax.swing.JLabel email_label_pwd_reset;
    private javax.swing.JLabel error_email_pwd_reset;
    private javax.swing.JLabel error_email_signup;
    private javax.swing.JLabel error_login;
    private javax.swing.JLabel error_password_signup;
    private javax.swing.JLabel error_username_signup;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField label_pwd_reset;
    private javax.swing.JTextField label_pwd_reset1;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField password_field_login;
    private javax.swing.JPasswordField password_field_signup;
    private javax.swing.JButton signup_btn;
    private javax.swing.JButton submit_btn;
    private javax.swing.JButton upload_btn;
    private javax.swing.JTextField username_textfield_login;
    private javax.swing.JTextField username_textfield_signup;
    // End of variables declaration//GEN-END:variables
}
